networks:
  mw-admin:
    driver: bridge

volumes:
  mw-admin-db:
    driver: local # Persistent storage for db
  mw-admin-redis:
    driver: local  # Persistent storage for Redis

services:
  db:
    image: postgres:alpine
    container_name: mw-admin-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_DB=mw-admin-db
      - POSTGRES_USER=mw-admin-usr
      - POSTGRES_PASSWORD=mw-admin-pwd
    networks:
      - mw-admin
    ports:
      - 5432:5432
    volumes:
      - mw-admin-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: mw-admin-redis
    networks:
      - mw-admin
    ports:
      - 6379:6379
    volumes:
      - mw-admin-redis:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mw-admin-app
    depends_on: # Ensures that services start before the app tries to connect
      - db
      - redis
    networks:
      - mw-admin
    ports:
      - 8080:8080
